# Generated by Django 3.0.3 on 2020-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='app.AppPicture/bytes/filename/mimetype')),
                ('info', models.TextField()),
            ],
        ),
    ]
