# Generated by Django 3.0.3 on 2020-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_portfoliocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='info',
            field=models.TextField(default='Не указано'),
        ),
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.CharField(default='Не указано', max_length=100),
        ),
    ]
