# Generated by Django 3.0.3 on 2020-02-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200215_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocard',
            name='full_description',
            field=models.TextField(default='Не указано'),
        ),
    ]
