# Generated by Django 3.0.3 on 2020-02-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_portfoliocard_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='full_description',
            field=models.TextField(default='Не указано'),
        ),
    ]
