# Generated by Django 3.0.3 on 2020-02-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_portfolioapppicture_portfoliopicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopicture',
            name='portfolio_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PortfolioCard'),
        ),
    ]
